version: '3.8'

services:
    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel-network

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        environment:
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel_user
            - DB_PASSWORD=laravel_password
        depends_on:
            - postgres
        networks:
            - laravel-network

    postgres:
        image: postgres:15
        container_name: laravel_postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laravel_user
            POSTGRES_PASSWORD: laravel_password
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel-network

volumes:
    postgres_data:

networks:
    laravel-network:
        driver: bridge
